version: 2
orbs:
  node: circleci/node@1.1.6
jobs:
  build_bridge:
    working_directory: ~/scatter-bridge
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
    - run: echo $CI_FONTAWESOME_1$'\n'$CI_FONTAWESOME_2 > .npmrc
    - run: yarn
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - run: yarn build
      # There will always only be one release
    - run: shasum -a 256 releases/Bridge.*.zip
    - run: ls -lh releases
    - store_artifacts:
        path: releases


workflows:
  version: 2
  build:
    jobs:
    - build_bridge:
        filters:
          branches:
            only: master
